### ISSUE TITLE
Cannot compilue under Ubuntu Trusty 14.04

### ISSUE THREAD

**Issue by StuxSoftware** [FFMS/ffms2#234]
```
src/core/track.cpp: In lambda function:
src/core/track.cpp:243:34: error: ‘av_rescale’ was not declared in this scope
   return av_rescale(Dur, Num, Den);
                                  ^
src/core/track.cpp: In member function ‘void FFMS_Track::FillAudioGaps()’:
src/core/track.cpp:247:73: error: ‘const void ExpectedSamples’ has incomplete type
  const auto ExpectedSamples = DurationToSamples(back().PTS - front().PTS);
                                                                         ^
src/core/track.cpp:269:74: error: ‘const void ExpectedStartSample’ has incomplete type
   const auto ExpectedStartSample = DurationToSamples(Frame.PTS - FirstPTS);
                                                                          ^
make: *** [src/core/track.lo] Error 1
```

**Comment by sonicarg** [comment]
The following fixes should be done in order to compile in Ubuntu 14.04:
 - `src/core/track.cpp`: insert `#include <libavutil/mathematics.h>` at line 30 (end of list of `#include`).
 - `include/ffmscompat.h`: change lines 90-91 with:

```
#		include <libavutil/pixdesc.h>
#		define FFMS_PIX_FMT(x) PIX_FMT_##x
#		define FFMS_PIX_FMT_FLAG(x) PIX_FMT_##x
```

The only step I can't make through by now is building `src/index/ffmsindex`, which requires undefined (just not found) symbols `av_get_pix_fmt(char const*)` and `av_rescale(long, long, long)`. If I find both symbols, then I'd be able to finish building.
